# Generated by Django 6.0 on 2026-02-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('learning', models.TextField()),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='blogs/certificates/')),
            ],
        ),
    ]
