# Generated by Django 6.0 on 2026-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
